---
- name: Install Dependencies (Linux)
  become: true
  dnf:
    name:
      - gh
      - git
      - zsh
      - npm
      - gcc
      - entr
      - curl
      - tree
      - make
      - sbcl
      - unzip
      - pdftk
      - sqlite
      - rlwrap
      - neovim
      - podman
      - direnv
      - fd-find
      - ghostty
      - ripgrep
      - lazygit
      - opentofu
      - cpanminus
      - gmp-devel
      - dbeaver-ce
      - glibc-devel
      - python3-pip
      - libffi-devel
      - openssl-devel
      - libyaml-devel
      - readline-devel
      - pkgconf-pkg-config
    state: present
  when: ansible_facts["os_family"] == "RedHat"

- name: Enable Repositories On Brew
  community.general.homebrew_tap:
    name: "{{ item }}"
    state: present
  loop:
    - sqitchers/sqitch
  when: ansible_facts["os_family"] == "Darwin"

- name: Install Dependencies For Work (macOS)
  community.general.homebrew:
    name:
      - jq
      - fd
      - gh
      - gcc
      - zsh
      - git
      - npm
      - gmp
      - entr
      - grip
      - rust
      - make
      - curl
      - tree
      - cmake
      - shfmt
      - unzip
      - direnv
      - awscli
      - pandoc
      - rlwrap
      - neovim
      - podman
      - golang
      - direnv
      - lazygit
      - ripgrep
      - libtool
      - libyaml
      - ghostty
      - coursier
      - opentofu
      - openssl@3
      - shellcheck
      - clojure-lsp
      - aws-sam-cli
      - font-fira-code
      - lua-language-server
    state: present
  when:
    - not akeptous_file.stat.exists
    - ansible_facts["os_family"] == "Darwin"

- name: Install Dependencies (macOS)
  community.general.homebrew:
    name:
      - jq
      - fd
      - gh
      - zsh
      - git
      - npm
      - gmp
      - entr
      - sbcl
      - curl
      - grip
      - perl
      - lima
      - tree
      - cmake
      - shfmt
      - unzip
      - sqlite
      - sqitch
      - pandoc
      - rlwrap
      - neovim
      - podman
      - direnv
      - lazygit
      - libtool
      - ripgrep
      - libyaml
      - ghostty
      - opentofu
      - cpanminus
      - openssl@3
      - shellcheck
      - font-fira-code
      - dbeaver-community
      - lua-language-server
    state: present
  when:
    - akeptous_file.stat.exists
    - ansible_facts["os_family"] == "Darwin"

- name: Install Perl Dependencies (macOS)
  become: true
  command: >
    /opt/homebrew/bin/cpanm
    --local-lib="/{{ base_dir }}/{{ current_user }}/.perl"
    --force
    DBI
    DBD::SQLite
  args:
    creates: "/{{ base_dir }}/{{ current_user }}/.perl"
  when:
    - akeptous_file.stat.exists
    - ansible_facts["os_family"] == "Darwin"

- name: Install Perl Dependencies (Linux)
  become: true
  community.general.cpanm:
    name: "{{ item }}"
  loop:
    - DBI
    - DBD::SQLite
    - App::Sqitch
  when:
    - akeptous_file.stat.exists
    - ansible_facts["os_family"] == "RedHat"

- name: Install Brave (Linux)
  shell: curl -fsS https://dl.brave.com/install.sh | sh
  args:
    creates: "/usr/bin/brave-browser"
  when: ansible_facts["os_family"] == "RedHat"

- name: Install Common Cask Dependencies (macOS)
  community.general.homebrew_cask:
    name: arc
    state: present
  when: ansible_facts["os_family"] == "Darwin"

- name: Set Zsh As Shell By Default
  become: true
  user:
    name: "{{ current_user }}"
    shell: /bin/zsh
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_file: ".ssh/{{ current_user }}_rsa"

- name: Install Ohmyzsh
  block:
    - name: Install Ohmyzsh - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh.sh
        mode: 0777
    - name: Install Ohmyzsh - Run Installer
      shell: |
        echo "Y" | sh /tmp/ohmyzsh.sh
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.oh-my-zsh"

- name: Rename Zprofile File
  block:
    - name: Rename Zprofile File - Verify Operation
      stat:
        path: "/{{ base_dir }}/{{ current_user }}/.zshrc"
      register: zprofile_file
    - name: Rename Zprofile File - Execute Operation
      command: >
        mv
        "/{{ base_dir }}/{{ current_user }}/.zprofile"
        "/{{ base_dir }}/{{ current_user }}/.zprofile--"
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.zprofile--"
      when: zprofile_file.stat.exists

- name: Rename Zshrc File
  block:
    - name: Rename Zshrc File - Verify Operation
      stat:
        path: "/{{ base_dir }}/{{ current_user }}/.zshrc"
      register: zshrc_file
    - name: Rename Zshrc File - Execute Operation
      command: >
        mv
        "/{{ base_dir }}/{{ current_user }}/.zshrc"
        "/{{ base_dir }}/{{ current_user }}/.zshrc--"
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.zshrc--"
      when: zshrc_file.stat.exists

- name: Configure Ghostty
  file:
    path: "/{{ base_dir }}/{{ current_user }}/.config/ghostty"
    state: directory
    mode: 0755
