---
- name: Install Common Dependencies (Linux)
  become: true
  dnf:
    name:
      - git
      - zsh
      - curl
      - tree
      - pdftk
      - rlwrap
      - lazygit
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Common Dependencies (macOS)
  community.general.homebrew:
    name:
      - git
      - zsh
      - curl
      - tree
      - rlwrap
      - lazygit
    state: present
  when: ansible_os_family == "Darwin"

- name: Set Zsh As Shell By Default
  become: true
  user:
    name: "{{ current_user }}"
    shell: /bin/zsh
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_file: ".ssh/{{ current_user }}_rsa"

- name: Install Ohmyzsh
  block:
    - name: Install Ohmyzsh - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh.sh
        mode: 0777
    - name: Install Ohmyzsh - Run Installer
      shell: |
        echo "Y" | sh /tmp/ohmyzsh.sh
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.oh-my-zsh"

- name: Rename Zshrc File
  block:
    - name: Rename Zshrc File - Verify Operation
      stat:
        path: "/{{ base_dir }}/{{ current_user }}/.zshrc"
      register: zshrc_file
    - name: Rename Zshrc File - Execute Operation
      command: >
        mv
        "/{{ base_dir }}/{{ current_user }}/.zshrc"
        "/{{ base_dir }}/{{ current_user }}/.zshrc--"
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.zshrc--"
      when: zshrc_file.stat.exists

- name: Configure Ghostty
  block:
    - name: Configure Ghostty - Verify Operation
      stat:
        path: "/{{ base_dir }}/{{ current_user }}/.config/ghostty/config"
      register: ghostty_file
    - name: Rename Ghostty File - Execute Operation
      command: >
        mv
        "/{{ base_dir }}/{{ current_user }}/.config/ghostty/config"
        "/{{ base_dir }}/{{ current_user }}/.config/ghostty/config--"
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.config/ghostty/config--"
      when: ghostty_file.stat.exists
    - name: Set Terminal Symlink Ghostty - Execute Operation
      command: >
        ln -s -f
        "/{{ base_dir }}/{{ current_user }}/.dotfiles/ghostty/day"
        "/{{ base_dir }}/{{ current_user }}/.config/ghostty/config"
      args:
        chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
        creates: "/{{ base_dir }}/{{ current_user }}/.config/ghostty/config"
      notify: Reload Zsh Files
      when: ghostty_file.stat.exists
