---
- name: Install Common Dependencies (Linux)
  become: true
  dnf:
    name:
      - git
      - zsh
      - curl
      - tree
      - pdftk
      - rlwrap
      - lazygit
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Common Dependencies (macOS)
  community.general.homebrew:
    name:
      - git
      - zsh
      - curl
      - tree
      - rlwrap
      - lazygit
    state: present
  when: ansible_os_family == "Darwin"

- name: Install Common Cask Dependencies (macOS)
  community.general.homebrew_cask:
    name: arc
    state: present

- name: Set Zsh As Shell By Default
  become: true
  user:
    name: "{{ current_user }}"
    shell: /bin/zsh
    generate_ssh_key: true
    ssh_key_bits: 4096
    ssh_key_file: ".ssh/{{ current_user }}_rsa"

- name: Install Ohmyzsh
  block:
    - name: Install Ohmyzsh - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh.sh
        mode: 0777
    - name: Install Ohmyzsh - Run Installer
      shell: |
        echo "Y" | sh /tmp/ohmyzsh.sh
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.oh-my-zsh"

- name: Rename Zprofile File
  block:
    - name: Rename Zprofile File - Verify Operation
      stat:
        path: "/{{ base_dir }}/{{ current_user }}/.zshrc"
      register: zprofile_file
    - name: Rename Zprofile File - Execute Operation
      command: >
        mv
        "/{{ base_dir }}/{{ current_user }}/.zprofile"
        "/{{ base_dir }}/{{ current_user }}/.zprofile--"
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.zprofile--"
      when: zprofile_file.stat.exists

- name: Rename Zshrc File
  block:
    - name: Rename Zshrc File - Verify Operation
      stat:
        path: "/{{ base_dir }}/{{ current_user }}/.zshrc"
      register: zshrc_file
    - name: Rename Zshrc File - Execute Operation
      command: >
        mv
        "/{{ base_dir }}/{{ current_user }}/.zshrc"
        "/{{ base_dir }}/{{ current_user }}/.zshrc--"
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.zshrc--"
      when: zshrc_file.stat.exists

- name: Configure Ghostty
  file:
    path: "/{{ base_dir }}/{{ current_user }}/.config/ghostty"
    state: directory
    mode: 0755
