---

- hosts: workspace
  become: true

  tasks:
    - name: install-dependencies-for-programming
      dnf:
        name:
          - emacs
          - neovim
          - lua
          - fennel
          - clojure
          - jq
          - git
          - npm
          - nodejs
          - curl
          - containerd
          - podman
          - podman-compose
          - tree
          - stow
          - xclip
          - pdftk
          - rlwrap
          - direnv
          - ripgrep
          - java-latest-openjdk
          - cmake
          - libtool
          - grip
          - shellcheck
          - tidy
          - shfmt
          - pandoc
          # - virtualbox
          # - vagrant
          # - dockfmt
          # - stylelint
          # - js-beautify
        state: present

