#!/usr/bin/env bash

# Color codes for output
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color

# Logging functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1" >&2
}

prepare_brew() {
    [ ! -e /opt/homebrew/bin/brew ] &&
        log_info "Installing Brew" &&
        /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)" &&
        log_info "Enabling Brew" &&
        eval "$(/opt/homebrew/bin/brew shellenv)" &&
        export PATH="/opt/homebrew/bin:$PATH"
}

install_deps() {
    if command -v brew >/dev/null 2>&1; then
        [ ! -e /opt/homebrew/bin/ansible ] &&
            log_info "Installing Ansible" &&
            brew install ansible
        [ ! -e /opt/homebrew/bin/guile ] &&
            log_info "Installing Guile" &&
            brew install guile
    elif command -v dnf >/dev/null 2>&1; then
        [ ! -e /usr/bin/ansible ] &&
            log_info "Installing Ansible" &&
            sudo dnf install ansible
        [ ! -e /usr/bin/guile3.0 ] &&
            log_info "Installing Guile" &&
            sudo dnf install guile30
    else
        log_error "Could Not Detect Package Manager To Install Dependencies"
        return 1
    fi
}

main() {
    local os
    os="$(uname)"

    if [[ "$os" == "Darwin" && -e "$HOME/.nurc" ]]; then
        prepare_brew
        install_deps
        guile -L . systems/work/main.scm "$@"
    elif [[ "$os" == "Darwin" ]]; then
        prepare_brew
        install_deps
        guile -L . systems/macos/main.scm "$@"
    elif [[ "$os" == "Linux" ]]; then
        install_deps
        guile3.0 -L . systems/linux/main.scm "$@"
    else
        log_error "OS Not Supported"
        return 1
    fi
}

main "$@"
