---
- name: Install NPM Dependencies (NVIM)
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
    force: true
  loop:
    - elm
    - emmet-ls
    - elm-test
    - elm-format
    - typescript
    - bash-language-server
    - yaml-language-server
    - typescript-language-server
    - vscode-langservers-extracted
    - "@github/copilot-language-server"
    - "@elm-tooling/elm-language-server"
  when:
    - akeptous_file.stat.exists

- name: Install NPM Dependencies (DOOM)
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
    force: true
  loop:
    - prettier
    - stylelint
    - typescript
    - js-beautify
    - bash-language-server
    - yaml-language-server
    - typescript-language-server
    - vscode-langservers-extracted
    - "@github/copilot-language-server"
  when:
    - not akeptous_file.stat.exists

- name: Create Configuration Directory
  ansible.builtin.file:
    path: "/{{ base_dir }}/{{ current_user }}/.config"
    state: directory
    mode: 0755

- name: Set Editor Symlink (ZED)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/zed"
    "/{{ base_dir }}/{{ current_user }}/.config/zed"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/zed/settings.json"
  notify: Reload Zsh Files
  when:
    - akeptous_file.stat.exists

- name: Set Editor Symlink (NVIM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/nvim"
    "/{{ base_dir }}/{{ current_user }}/.config/nvim"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/nvim/init.lua"
  notify: Reload Zsh Files

- name: Set Editor Symlink (DOOM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/doom"
    "/{{ base_dir }}/{{ current_user }}/.config/doom"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/doom/init.el"
  notify: Reload Zsh Files
  when:
    - not akeptous_file.stat.exists
    - ansible_os_family == "Darwin"
