---
- name: Install Editors (Linux)
  become: true
  dnf:
    name:
      - neovim
      - emacs
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Editors (macOS)
  block:
    - name: Install Editors (macOS) - Emacs
      shell: >
        brew tap d12frosted/emacs-plus
        brew install emacs-plus --with-modern-doom3-icon --with-native-comp --with-mailutils
      args:
        creates: /opt/homebrew/Library/Taps/d12frosted/homebrew-emacs-plus
    - name: Install Editors (macOS) - Neovim
      community.general.homebrew:
        name:
          - neovim
        state: present
  when: ansible_os_family == "Darwin"

- name: Install Dependencies For Editors (Linux)
  become: true
  dnf:
    name:
      - jq
      - gh
      - gcc
      - make
      - grip
      - tidy
      - cmake
      - shfmt
      - unzip
      - xclip
      - pandoc
      - direnv
      - libtool
      - ghostty
      - ripgrep
      - fd-find
      - shellcheck
      - fira-code-fonts
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Dependencies For Editors (macOS)
  community.general.homebrew:
    name:
      - jq
      - gh
      - fd
      - gcc
      - make
      - grip
      - cmake
      - shfmt
      - unzip
      - pandoc
      - direnv
      - libtool
      - ripgrep
      - ghostty
      - shellcheck
    state: present
  when: ansible_os_family == "Darwin"

- name: Install NPM Dependencies
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - stylelint
    - js-beautify
    - prettier
    - bash-language-server
    - yaml-language-server
  when: akeptous_file.stat.exists

- name: Install Python Dependencies
  become: true
  pip:
    name:
      - black
      - pyflakes
      - isort
      - pipenv
      - nose
      - pytest
    executable: pip3

- name: Install Pyenv
  block:
    - name: Install Pyenv - Download Installer
      get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: /tmp/pyenv
        mode: 0777
    - name: Install Pyenv - Run Installer
      become: true
      shell: /tmp/pyenv
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.pyenv"

- name: Install Cljfmt
  block:
    - name: Install Cljfmt - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/weavejester/cljfmt/HEAD/install.sh
        dest: /tmp/cljfmt
        mode: 0777
    - name: Install Cljfmt - Run Installer
      become: true
      shell: /tmp/cljfmt
      args:
        creates: /usr/local/bin/cljfmt
  when: not akeptous_file.stat.exists

- name: Install Clojure LSP
  block:
    - name: Install Clojure LSP - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/clojure-lsp/clojure-lsp/master/install
        dest: /tmp/clojure-lsp
        mode: 0777
    - name: Install Clojure LSP - Run Installer
      become: true
      shell: /tmp/clojure-lsp
      args:
        creates: /usr/local/bin/clojure-lsp
  when: not akeptous_file.stat.exists

- name: Install Dockfmt
  become: true
  shell: |
    go install github.com/jessfraz/dockfmt@latest
    mv /root/go/bin/dockfmt /usr/local/bin/dockfmt
  args:
    creates: /usr/local/bin/dockfmt

- name: Set Editor Symlink (NVIM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/nvim"
    "/{{ base_dir }}/{{ current_user }}/.config/nvim"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/nvim/init.lua"
  notify: Reload Zsh Files

- name: Set Editor Symlink (DOOM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/doom"
    "/{{ base_dir }}/{{ current_user }}/.config/doom"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/doom/init.el"
  notify: Reload Zsh Files
