---
- name: Install Editors (Linux)
  become: true
  dnf:
    name:
      - zed
      - neovim
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Editors (macOS)
  community.general.homebrew:
    name:
      - zed
      - neovim
    state: present
  when: ansible_os_family == "Darwin"

- name: Install Dependencies For Editors (Linux)
  become: true
  dnf:
    name:
      - gcc
      - make
      - grip
      - tidy
      - cmake
      - shfmt
      - unzip
      - xclip
      - pandoc
      - libtool
      - ripgrep
      - fd-find
      - shellcheck
      - fira-code-fonts
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Dependencies For Editors (macOS)
  community.general.homebrew:
    name:
      - jq
      - gh
      - fd
      - gcc
      - make
      - grip
      - cmake
      - shfmt
      - unzip
      - pandoc
      - direnv
      - libtool
      - ripgrep
      - ghostty
      - shellcheck
      - font-fira-code
    state: present
  when: ansible_os_family == "Darwin"

- name: Install NPM Dependencies
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
    force: true
  loop:
    - prettier
    - stylelint
    - typescript
    - js-beautify
    - bash-language-server
    - yaml-language-server
    - typescript-language-server
    - vscode-langservers-extracted
    - "@github/copilot-language-server"

- name: Install Dockfmt (Linux)
  become: true
  shell: |
    mkdir /usr/local/bin/dockfmt
    go install github.com/jessfraz/dockfmt@latest
    mv /root/go/bin/dockfmt /usr/local/bin/dockfmt
  args:
    creates: /usr/local/bin/dockfmt
  when: ansible_os_family == "RedHat"

- name: Install Dockfmt (macOS)
  become: true
  shell: |
    go install github.com/jessfraz/dockfmt@latest
    mv /var/root/go/bin/dockfmt /usr/local/bin/dockfmt
  args:
    creates: /usr/local/bin/dockfmt
  when: ansible_os_family == "Darwin"

- name: Create Configuration Directory
  ansible.builtin.file:
    path: "/{{ base_dir }}/{{ current_user }}/.config"
    state: directory
    mode: 0755

- name: Set Editor Symlink (NVIM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/nvim"
    "/{{ base_dir }}/{{ current_user }}/.config/nvim"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/nvim/init.lua"
  notify: Reload Zsh Files

- name: Set Editor Symlink (DOOM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/doom"
    "/{{ base_dir }}/{{ current_user }}/.config/doom"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/doom/init.el"
  notify: Reload Zsh Files
