---
- hosts: Workspace

  vars_files:
    - vars/base.yml
    - vars/secret.yml

  tasks:
    - name: Install Dependencies
      community.general.homebrew:
        name:
          - stow
        state: present
    - import_tasks: ../common/tasks/environment.yml

  handlers:
    - import_tasks: ../common/handlers/base.yml
