---
- hosts: Workspace

  vars_files:
    - vars/common.yml

  tasks:
    - name: Install Dependencies
      community.general.homebrew:
        name:
          - stow
        state: present
    - import_tasks: tasks/environment.yml
    - import_tasks: ../common/tasks/environment.yml
