---
- hosts: Workstation

  vars_files:
    - akeptous/base.yml
    - akeptous/secret.yml

  pre_tasks:
    - name: Verify Akeptous Workstation
      stat:
        path: "/{{ base_dir }}/{{ current_user }}/.akeptous"
      register: akeptous_file

  roles:
    - base
    - development
    - editor
    - ai
    - environment
    - security
