---
- hosts: Workstation

  vars_files:
    - work/base.yml
    - work/secret.yml

  pre_tasks:
    - name: Verify Akeptous Workstation
      stat:
        path: "/{{ base_dir }}/{{ current_user }}/.akeptous"
      register: akeptous_file

  roles:
    - base
    - development
    - editor
    - environment
    - ai
