---
- name: Install Development Stack (Linux)
  become: true
  dnf:
    name:
      - npm
      - golang
      - dbeaver-ce
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Lima VM (Linux)
  block:
    - name: Install Lima VM (Linux) - Get Data
      uri:
        url: https://api.github.com/repos/lima-vm/lima/releases/latest
        method: GET
        return_content: yes
      register: lima_release
    - name: Install Lima VM (Linux) - Set Version
      set_fact:
        lima_version: "{{ lima_release.content | from_json | json_query('tag_name') }}"
    - name: Install Lima VM (Linux) - Install Binary
      become: true
      shell: |
        curl -fsSL "https://github.com/lima-vm/lima/releases/download/${VERSION}/lima-${VERSION:1}-Linux-x86_64.tar.gz" | tar Cxzvm /usr/local
        curl -fsSL "https://github.com/lima-vm/lima/releases/download/${VERSION}/lima-additional-guestagents-${VERSION:1}-Linux-x86_64.tar.gz" | tar Cxzvm /usr/local
      environment:
        VERSION: "{{ lima_version }}"
      args:
        creates: /usr/local/bin/limactl
  when: ansible_os_family == "RedHat"

- name: Install Development Stack (macOS)
  block:
    - name: Install Development Stack (macOS) - Add Tap
      community.general.homebrew_tap:
        name:
          - coursier/formulas
        state: present
    - name: Install Development Stack (macOS) - Run Brew
      community.general.homebrew:
        name:
          - go
          - npm
          - lima
          - coursier
          - dbeaver-community
        state: present
  when: akeptous_file.stat.exists and (ansible_os_family == "Darwin")

- name: Install Scala Setup
  shell: |
    echo "Y" | coursier setup
  args:
    creates: "/{{ base_dir }}/{{ current_user }}/Library/Application Support/Coursier/bin/scala"
  when: akeptous_file.stat.exists and (ansible_os_family == "Darwin")

- name: Install Scala Metals
  shell: |
    coursier install metals
  args:
    creates: "/{{ base_dir }}/{{ current_user }}/Library/Application Support/Coursier/bin/metals"
  when: akeptous_file.stat.exists and (ansible_os_family == "Darwin")

- name: Install Java
  shell: |
    coursier java --jvm=17 --setup
  args:
    creates: "/usr/bin/java"
  when: akeptous_file.stat.exists and (ansible_os_family == "Darwin")

- name: Install Clojure
  become: true
  block:
    - name: Install Clojure - Download Installer
      get_url:
        url: https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
        dest: /tmp/clojure-installer.sh
        mode: 0755
    - name: Install Clojure - Run Installer
      shell: /tmp/clojure-installer.sh
      args:
        creates: /usr/local/bin/clojure
  when: not akeptous_file.stat.exists

- name: Install Babashka
  block:
    - name: Install Babashka - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/babashka/babashka/master/install
        dest: /tmp/babashka
        mode: 0777
    - name: Install Babashka - Run Installer
      become: true
      shell: /tmp/babashka
      args:
        creates: /usr/local/bin/bb
  when: not akeptous_file.stat.exists
