---
- name: Install Development Stack (Linux)
  become: true
  dnf:
    name:
      - java-latest-openjdk
      - npm
      - nodejs
      - python3-pip
      - golang
      - podman
      - podman-compose
      - vagrant
      - dbeaver-ce
    state: present
  when: ansible_os_family == "RedHat"

- name: Install Clojure*
  become: true
  block:
    - name: Install Clojure - Download Installer
      get_url:
        url: https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
        dest: /tmp/clojure-installer.sh
        mode: 0755
    - name: Install Clojure - Run Installer
      shell: /tmp/clojure-installer.sh
      args:
        creates: /usr/local/bin/clojure
  when: ansible_os_family == "Darwin"

- name: Install Babashka*
  block:
    - name: Install Babashka - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/babashka/babashka/master/install
        dest: /tmp/babashka
        mode: 0777
    - name: Install Babashka - Run Installer
      become: true
      shell: /tmp/babashka
      args:
        creates: /usr/local/bin/bb
  when: ansible_os_family == "Darwin"  

- name: Install Bun*
  block:
    - name: Install Bun - Download Installer
      get_url:
        url: https://bun.sh/install
        dest: /tmp/bun-installer
        mode: 0777
    - name: Install Bun - Run Installer
      become: true
      shell: /tmp/bun-installer
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.bun/_bun"
