---
- name: Install Mise
  shell: |
    curl https://mise.run | sh
  args:
    creates: "/{{ base_dir }}/{{ current_user }}/.local/bin/mise"
  notify: Reload Zsh Files
  when: akeptous_file.stat.exists

- name: Install Ruby
  command: >
    mise use -g ruby@3
  args:
    creates: "/usr/bin/ruby"
  notify: Reload Zsh Files
  when: akeptous_file.stat.exists

- name: Install Gems
  gem:
    name: "{{ item }}"
    state: present
  loop:
    - thor
    - rails
    - rubocop
    - solargraph
  notify: Reload Zsh Files
  when: akeptous_file.stat.exists

- name: Install NVM
  shell: |
    curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh" | bash
  args:
    creates: "/{{ base_dir }}/{{ current_user }}/.nvm/nvm.sh"
  when: akeptous_file.stat.exists

- name: Install Java
  shell: |
    coursier java "--jvm={{ jvm_version }}" --setup
  args:
    creates: "/usr/bin/java"
  when:
    - not akeptous_file.stat.exists
    - ansible_os_family == "Darwin"

- name: Install Clojure
  become: true
  block:
    - name: Install Clojure - Download Installer
      get_url:
        url: https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
        dest: /tmp/clojure-installer.sh
        mode: 0755
    - name: Install Clojure - Run Installer
      shell: /tmp/clojure-installer.sh
      args:
        creates: /usr/local/bin/clojure
  when:
    - not akeptous_file.stat.exists
    - ansible_os_family == "Darwin"

- name: Install Babashka
  block:
    - name: Install Babashka - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/babashka/babashka/master/install
        dest: /tmp/babashka
        mode: 0777
    - name: Install Babashka - Run Installer
      become: true
      shell: /tmp/babashka
      args:
        creates: /usr/local/bin/bb
  when:
    - not akeptous_file.stat.exists
    - ansible_os_family == "Darwin"
