---
- name: Install Coursier (Linux) - Check Binary
  stat:
    path: /usr/local/bin/coursier
  register: coursier_binary

- name: Install Coursier (Linux)
  block:
    - name: Install Coursier (Linux) - Download Binary
      shell: |
        curl -fL "https://github.com/coursier/launchers/raw/master/cs-x86_64-pc-linux.gz" | gzip -d > coursier
      args:
        chdir: /tmp
    - name: Install Coursier (Linux) - Install Binary
      become: true
      copy:
        src: /tmp/coursier
        dest: /usr/local/bin/coursier
        mode: 0755
        force: false
  when:
    - not coursier_binary.stat.exists
    - akeptous_file.stat.exists
    - ansible_os_family == "RedHat"

- name: Install NVM
  shell: |
    curl -o- "https://raw.githubusercontent.com/nvm-sh/nvm/v{{ nvm_version }}/install.sh" | bash
  args:
    creates: "/{{ base_dir }}/{{ current_user }}/.nvm/nvm.sh"
  when: akeptous_file.stat.exists

- name: Install Java
  shell: |
    coursier java "--jvm={{ jvm_version }}" --setup
  args:
    creates: "/usr/bin/java"
  when:
    - akeptous_file.stat.exists

- name: Install Clojure
  become: true
  block:
    - name: Install Clojure - Download Installer
      get_url:
        url: https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
        dest: /tmp/clojure-installer.sh
        mode: 0755
    - name: Install Clojure - Run Installer
      shell: /tmp/clojure-installer.sh
      args:
        creates: /usr/local/bin/clojure

- name: Install Babashka
  block:
    - name: Install Babashka - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/babashka/babashka/master/install
        dest: /tmp/babashka
        mode: 0777
    - name: Install Babashka - Run Installer
      become: true
      shell: /tmp/babashka
      args:
        creates: /usr/local/bin/bb

- name: Install Cljfmt
  become: true
  shell: |
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/weavejester/cljfmt/HEAD/install.sh)"
  args:
    creates: /usr/local/bin/cljfmt

- name: Install Scala Metals
  shell: |
    coursier install metals
  args:
    creates: "/{{ base_dir }}/{{ current_user }}/{{ coursier_path }}/metals"
  when: not akeptous_file.stat.exists

- name: Install Scalafmt
  shell: |
    coursier install scalafmt
  args:
    creates: "/{{ base_dir }}/{{ current_user }}/{{ coursier_path }}/scalafmt"
  when: not akeptous_file.stat.exists
