---
- name: Install Aider
  block:
    - name: Install Aider - Download Installer (Linux)
      pip:
        name: aider-install
        state: present
      when: ansible_os_family == "RedHat"
    - name: Install Aider - Download Installer (macOS)
      shell: curl -LsSf https://aider.chat/install.sh | sh
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.local/bin/aider"
      when: ansible_os_family == "Darwin"
    - name: Install Aider - Run Installer
      shell: aider-install
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.local/bin/aider"
