---
- name: Install Aider
  block:
    - name: Install Aider - Download Installer (Linux)
      pip:
        name: aider-install
        state: present
      when: ansible_os_family == "RedHat"
    - name: Install Aider - Download Installer (macOS)
      shell: curl -LsSf https://aider.chat/install.sh | sh
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.local/bin/aider"
      when: ansible_os_family == "Darwin"
    - name: Install Aider - Run Installer
      shell: aider-install
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.local/bin/aider"

- name: Propagate GitHub Token
  lineinfile:
    create: true
    line: "export GITHUB_TOKEN={{ github_token }}"
    path: "/{{ base_dir }}/{{ current_user }}/.dotfiles/.private_profile"
  notify: Reload Zsh Files
  when: akeptous_file.stat.exists

- name: Propagate Gemini Api Key
  lineinfile:
    create: true
    line: "export GEMINI_API_KEY={{ gemini_api_key }}"
    path: "/{{ base_dir }}/{{ current_user }}/.dotfiles/.private_profile"
  notify: Reload Zsh Files
  when: akeptous_file.stat.exists

- name: Propagate Anthropic Api Key
  lineinfile:
    create: true
    line: "export ANTHROPIC_API_KEY={{ anthropic_api_key }}"
    path: "/{{ base_dir }}/{{ current_user }}/.dotfiles/.private_profile"
  notify: Reload Zsh Files
  when: akeptous_file.stat.exists
