# BASIC CONFIGURATION
# -------------------

export PATH="/usr/local/bin:$PATH"
export PATH="/usr/local/sbin:$PATH"
export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/usr/local/opt/curl/bin:$PATH"

export PATH="/opt/homebrew/bin:$PATH"
export PATH="/opt/homebrew/sbin:$PATH"
export PATH="/usr/local/opt/file-formula/bin:$PATH"
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv >/dev/null || export PATH="$PYENV_ROOT/bin:$PATH"
eval "$(pyenv init -)"
export PATH="/usr/local/opt/file-formula/bin:$PATH"
export NU_HOME="${HOME}/dev/nu"
export NUCLI_HOME="${NU_HOME}/nucli"
export PATH="${NUCLI_HOME}:${PATH}"

export PATH="$HOME/.config/emacs/bin:$PATH"
if [ -d "$(brew --prefix)/opt/grep/libexec/gnubin" ]; then
    PATH="$(brew --prefix)/opt/grep/libexec/gnubin:$PATH"
fi

# PERSONAL CONFIGURATION
# ----------------------

nu-refresh() {
    nu update

    nu-co certs setup --env prod
    nu-co certs setup --env staging
    nu-co auth get-refresh-token --env=prod --force
    nu-co auth get-access-token --env prod
    nu-co auth jwt --env prod
    nu-co auth jwt --env staging
    nu-co auth get-refresh-token --env prod --force
    nu-co auth get-refresh-token --env staging --force
    nu-co auth get-access-token --env prod
    nu-co auth get-access-token --env staging
    # nu-co sec scope show xavier.ramirez --env prod
    # nu-co sec scope show xavier.ramirez --env staging

    nu aws credentials refresh
    # nu aws shared-role-credentials refresh --account-alias=br
    nu aws shared-role-credentials refresh --account-alias co
    nu codeartifact login maven
    nu codeartifact login npm

    nu-ist certs setup --env prod
    nu-ist certs setup --env staging
    nu-ist auth get-refresh-token --env prod --force
    nu-ist auth get-access-token --env prod
    nu-ist auth get-refresh-token --env staging --force
    nu-ist auth get-access-token --env staging

    nu-ist sec scope add xavier.ramirez admin --env staging
    nu-ist-staging certs setup

    nu-br-staging certs setup
    nu-br-staging auth get-refresh-token
    nu-br-staging auth get-access-token

    nu-br certs setup --env prod
    nu-br certs setup --env staging
    nu-br auth get-refresh-token --env prod --force
    nu-br auth get-refresh-token --env staging --force
    nu-br auth get-access-token --env prod
    nu-br auth get-access-token --env staging

    nu-mx certs setup --env prod
    nu-mx certs setup --env staging
    nu-mx auth get-refresh-token --env prod --force
    nu-mx auth get-refresh-token --env staging --force
    nu-mx auth get-access-token --env prod
    nu-mx auth get-access-token --env staging

    nu-data certs setup --env staging
    nu-data certs setup --env prod
    nu-data auth get-refresh-token --env prod --force
    nu-data auth get-refresh-token --env staging --force
    nu-data auth get-access-token --env prod
    nu-data auth get-access-token --env staging
}

nu-start() {
    nu update
    nu aws credentials refresh
    nu aws shared-role-credentials refresh --account-alias br
    nu cert setup --country co --env staging
    nu-co auth get-refresh-token --env prod
    nu-co auth get-access-token --env prod
    nu-co auth jwt --env prod
    nu-co sec scope show xavier.ramirez --env prod
    nu-co auth get-refresh-token --env staging
    nu-co auth get-access-token --env staging
    nu-co auth jwt --env staging
    nu-co sec scope show xavier.ramirez --env staging
    nu-ist auth get-refresh-token --env staging
    nu-ist auth get-access-token --env staging
    nu-ist sec scope add xavier.ramirez admin --env staging
    nu codeartifact login maven
    nu codeartifact login npm
}
