---
- name: Install Emacs And Neovim
  become: true
  dnf:
    name:
      - emacs
      - neovim
    state: present

- name: Install Dependencies For Emacs
  become: true
  dnf:
    name:
      - ripgrep
      - cmake
      - libtool
      - grip
      - shellcheck
      - tidy
      - shfmt
      - pandoc
      # - dockfmt
    state: present

- name: Install NPM Dependencies
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - bash-language-server
    - yaml-language-server
