---
- name: Install Emacs And Neovim
  become: true
  dnf:
    name:
      - emacs
      - neovim
    state: present

- name: Install Dependencies For Emacs
  become: true
  dnf:
    name:
      - ripgrep
      - cmake
      - libtool
      - grip
      - shellcheck
      - tidy
      - shfmt
      - pandoc
      - nodejs-bash-language-server
      # - dockfmt
    state: present
# - name: Install NPM Dependencies
#   become: true
#   community.general.npm:
#     name: "{{ item }}"
#     global: true
#   loop:
#     - stylelint
#     - js-beautify
#     - prettier
#     - "@prettier/plugin-ruby"
