---
- name: Add Ssh Key To Agent
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add "/home/{{ current_user }}/.ssh/{{ current_user }}_rsa"
  args:
    executable: /bin/bash
    creates: "/home/{{ current_user }}/.ssh/{{ current_user }}_rsa"

- name: Add Git Configuration
  community.general.git_config:
    name: user.email
    scope: global
    value: bxsr@proton.me
