---
- name: Install Stack
  dnf:
    name:
      - lua
      - luarocks
      - fennel
      - clojure
      - java-latest-openjdk
      - npm
      - nodejs
      - containerd
      - podman
      - podman-compose
      - vagrant
      - dbeaver-ce
    state: present

- name: Install Babashka
  block:
    - name: Install Babashka - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/babashka/babashka/master/install
        dest: /tmp/babashka
        mode: 0777
    - name: Install Babashka - Run Installer
      shell: /tmp/babashka
      args:
        creates: /usr/local/bin/bb

- name: Install Cljfmt
  block:
    - name: Install Cljfmt - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/weavejester/cljfmt/HEAD/install.sh
        dest: /tmp/cljfmt
        mode: 0777
    - name: Install Cljfmt - Run Installer
      shell: /tmp/cljfmt
      args:
        creates: /usr/local/bin/cljfmt

- name: Install Clojure-lsp
  block:
    - name: Install Clojure-lsp - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/clojure-lsp/clojure-lsp/master/install
        dest: /tmp/clojure-lsp
        mode: 0777
    - name: Install Clojure-lsp - Run Installer
      shell: /tmp/clojure-lsp
      args:
        creates: /usr/local/bin/clojure-lsp
