---
- name: Install Stack
  become: true
  dnf:
    name:
      - rbenv
      - ruby-devel
      - podman
      - podman-compose
      - vagrant
      - dbeaver-ce
    state: present

- name: Install Ruby Dependencies
  community.general.gem:
    name: "{{ item }}"
    user_install: false
    state: latest
  loop:
    - solargraph
    - bundler
    - rubocop
