---
- name: Install Stack
  become: true
  dnf:
    name:
      - rbenv
      - ruby-devel
      - podman
      - podman-compose
      - vagrant
      - dbeaver-ce
    state: present

- name: Install Ruby Dependencies
  become: true
  community.general.gem:
    name: "{{ item }}"
    user_install: false
    bindir: "/usr/local/bin"
    state: latest
  loop:
    - ruby-lsp
    - rails

