---
- name: Propagate Current User
  lineinfile:
    regexp: "^export CURRENT_USER="
    line: "export CURRENT_USER={{ current_user }}"
    path: "/{{ base_dir }}/{{ current_user }}/.dotfiles/.{{ workspace_id }}_profile"
  notify: Reload Zsh Files

- name: Propagate Token
  lineinfile:
    create: true
    line: "export GITHUB_TOKEN={{ github_token }}"
    path: "/{{ base_dir }}/{{ current_user }}/.dotfiles/.private_profile"
  notify: Reload Zsh Files

- name: Set Symlinks
  command: >
    stow .
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
  notify: Reload Zsh Files

- name: Set Symlinks
  shell: |
    ln -s -f "/{{ base_dir }}/{{ current_user }}/.dotfiles/.{{ workspace_id }}rc" "/{{ base_dir }}/{{ current_user }}/.{{ workspace_id }}rc"
    ln -s -f "/{{ base_dir }}/{{ current_user }}/.dotfiles/.{{ workspace_id }}_profile" "/{{ base_dir }}/{{ current_user }}/.{{ workspace_id }}_profile"
    ln -s -f "/{{ base_dir }}/{{ current_user }}/.dotfiles/.private_profile" "/{{ base_dir }}/{{ current_user }}/.private_profile"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.{{ workspace_id }}_profile"
  notify: Reload Zsh Files
