---
- name: Install Editors
  become: true
  dnf:
    name:
      - neovim
      - emacs
    state: present

- name: Install Dependencies For Editors
  become: true
  dnf:
    name:
      - jq
      - gh
      - gcc
      - make
      - grip
      - tidy
      - cmake
      - shfmt
      - unzip
      - xclip
      - pandoc
      - direnv
      - libtool
      - ghostty
      - ripgrep
      - fd-find
      - shellcheck
      - fira-code-fonts
    state: present

- name: Install NPM Dependencies
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - stylelint
    - js-beautify
    - bash-language-server
    - yaml-language-server

- name: Set Editor Symlink (NVIM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/nvim"
    "/{{ base_dir }}/{{ current_user }}/.config/nvim"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/nvim/init.lua"
  notify: Reload Zsh Files

- name: Set Editor Symlink (DOOM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/doom"
    "/{{ base_dir }}/{{ current_user }}/.config/doom"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/doom/init.el"
  notify: Reload Zsh Files
