---
- name: Install Neovim
  become: true
  dnf:
    name:
      - neovim
    state: present

- name: Install Neovim Dependencies
  become: true
  dnf:
    name:
      - jq
      - gh
      - ripgrep
      - make
      - libtool
      - grip
      - shellcheck
      - tidy
      - shfmt
      - fd-find
      - gcc
      - unzip
      - direnv
      - xclip
      - ghostty
      - fira-code-fonts
    state: present

- name: Install NPM Dependencies
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - bash-language-server
    - yaml-language-server

- name: Set Editor Symlink (NVIM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/nvim"
    "/{{ base_dir }}/{{ current_user }}/.config/nvim"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/nvim/init.lua"
  notify: Reload Zsh Files
