---
- name: Install Editors
  become: true
  dnf:
    name:
      - neovim
      - emacs
    state: present

- name: Install Dependencies For Editors
  become: true
  dnf:
    name:
      - jq
      - gh
      - gcc
      - make
      - grip
      - tidy
      - cmake
      - shfmt
      - unzip
      - xclip
      - pandoc
      - direnv
      - libtool
      - ghostty
      - ripgrep
      - fd-find
      - shellcheck
      - fira-code-fonts
    state: present

- name: Install NPM Dependencies
  become: true
  community.general.npm:
    name: "{{ item }}"
    global: true
  loop:
    - stylelint
    - js-beautify
    - bash-language-server
    - yaml-language-server

- name: Install Python Dependencies
  become: true
  pip:
    name:
      - black
      - pyflakes
      - isort
      - pipenv
      - nose
      - pytest
    executable: pip3

- name: Install Pyenv
  block:
    - name: Install Pyenv - Download Installer
      get_url:
        url: https://github.com/pyenv/pyenv-installer/raw/master/bin/pyenv-installer
        dest: /tmp/pyenv
        mode: 0777
    - name: Install Pyenv - Run Installer
      become: true
      shell: /tmp/pyenv
      args:
        creates: "/{{ base_dir }}/{{ current_user }}/.pyenv"

- name: Install Cljfmt
  block:
    - name: Install Cljfmt - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/weavejester/cljfmt/HEAD/install.sh
        dest: /tmp/cljfmt
        mode: 0777
    - name: Install Cljfmt - Run Installer
      become: true
      shell: /tmp/cljfmt
      args:
        creates: /usr/local/bin/cljfmt

- name: Install Clojure LSP
  block:
    - name: Install Clojure LSP - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/clojure-lsp/clojure-lsp/master/install
        dest: /tmp/clojure-lsp
        mode: 0777
    - name: Install Clojure LSP - Run Installer
      become: true
      shell: /tmp/clojure-lsp
      args:
        creates: /usr/local/bin/clojure-lsp

- name: Set Editor Symlink (NVIM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/nvim"
    "/{{ base_dir }}/{{ current_user }}/.config/nvim"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/nvim/init.lua"
  notify: Reload Zsh Files

- name: Set Editor Symlink (DOOM)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/doom"
    "/{{ base_dir }}/{{ current_user }}/.config/doom"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.config/doom/init.el"
  notify: Reload Zsh Files
