---
- name: Install Stack
  become: true
  dnf:
    name:
      - clojure
      - java-latest-openjdk
      - npm
      - nodejs
      - python3-pip
      - golang
      - podman
      - podman-compose
      - vagrant
      - dbeaver-ce
    state: present

- name: Install Babashka
  block:
    - name: Install Babashka - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/babashka/babashka/master/install
        dest: /tmp/babashka
        mode: 0777
    - name: Install Babashka - Run Installer
      become: true
      shell: /tmp/babashka
      args:
        creates: /usr/local/bin/bb

