---
- name: Install Stack
  become: true
  dnf:
    name:
      - clojure
      - java-latest-openjdk
      - npm
      - nodejs
      - python3-pip
      - golang
      - podman
      - podman-compose
      - vagrant
      - dbeaver-ce
    state: present

- name: Install Babashka
  block:
    - name: Install Babashka - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/babashka/babashka/master/install
        dest: /tmp/babashka
        mode: 0777
    - name: Install Babashka - Run Installer
      become: true
      shell: /tmp/babashka
      args:
        creates: /usr/local/bin/bb

- name: Install Polylith
  become: true
  block:
    - name: Install Polylith - Download Installer
      get_url:
        url: https://github.com/polyfy/polylith/releases/download/v0.2.22/poly-0.2.22.jar
        dest: /usr/local/polylith
        mode: 0777
    - name: Install Polylith - Set Symlink To CLI
      command: >
        ln -s -f
        "/{{ base_dir }}/{{ current_user }}/.dotfiles/polytith"
        /usr/local/bin/polylith
      args:
        creates: /usr/local/bin/polylith
      notify: Reload Zsh Files
