---
- name: Install Ghostty (Linux)
  become: true
  community.general.snap:
    name: ghostty
    classic: true
  when: ansible_facts["os_family"] == "Debian"

- name: Install DBeaver (Linux)
  become: true
  community.general.snap:
    name: dbeaver-ce
    classic: true
  when: ansible_facts["os_family"] == "Debian"

- name: Install Emacs (Linux)
  become: true
  community.general.snap:
    name: emacs
    classic: true
  when: ansible_facts["os_family"] == "Debian"
