---
- name: Create SSH Directory
  ansible.builtin.file:
    path: "/{{ base_dir }}/{{ current_user }}/.ssh"
    state: directory
    mode: 0755

- name: Add Ssh Key To Agent
  become: true
  shell: |
    eval "$(ssh-agent -s)"
    ssh-add "/home/{{ current_user }}/.ssh/{{ current_user }}_rsa"
  args:
    executable: /bin/bash
    creates: "/home/{{ current_user }}/.ssh/{{ current_user }}_rsa"
  when: akeptous_file.stat.exists

- name: Add Git Configuration
  community.general.git_config:
    name: user.email
    scope: global
    value: bxsr@proton.me
  when: akeptous_file.stat.exists
