---

- name: Install Common Dependencies
  dnf:
    name:
      - neovim
      - jq
      - git
      - curl
      - tree
      - stow
      - xclip
      - pdftk
      - rlwrap
      - direnv
    state: present
