---
- name: Install Common Dependencies
  dnf:
    name:
      - jq
      - git
      - zsh
      - curl
      - tree
      - stow
      - xclip
      - pdftk
      - rlwrap
      - direnv
      - neovim
      - ghostty
      - fira-code-fonts
    state: present

- name: Set Zsh As Shell By Default
  expect:
    command: chsh -s /usr/bin/zsh
    responses:
      (?i)password: "{{ password }}"

- name: Install Ohmyzsh
  block:
    - name: Install Ohmyzsh - Download Installer
      get_url:
        url: https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh
        dest: /tmp/ohmyzsh.sh
        mode: 0777
    - name: Install Ohmyzsh - Run Installer
      shell: echo "Y" | /tmp/ohmyzsh.sh
      args:
        creates: ~/.oh-my-zsh
