---
- name: Install Emacs
  dnf: name=emacs state=present
  
- name: Install Zed
  block:
    - name: Install Zed - Download Installer
      get_url:
        url: https://zed.dev/install.sh
        dest: /tmp/zed.sh
        mode: 0777
    - name: Install Zed - Run Installer
      shell: /tmp/zed.sh
      args:
        executable: /bin/bash
        creates: ~/.local/bin/zed


- name: Install Doom
  block:
    - name: Install Doom - Varify Installation
      stat:
        path: ~/.config/emacs/bin/doom
      register: has_doom_installed
      changed_when: false
    - name: Install Doom - Clone Repository
      git:
        repo: https://github.com/doomemacs/doomemacs
        dest: ~/.config/emacs
        depth: 1
      when: not has_doom_installed.stat.exists
    - name: Install Doom - Run Install Script
      command: >
        ~/.config/emacs/bin/doom install
      when: not has_doom_installed.stat.exists
    - name: Install Doom - Change Icon
      shell: |
        mkdir -p "$HOME/.local/share/icons"
        ICON="$HOME/.local/share/icons/doom.png"
        DESKTOP_FILE=/usr/share/applications/emacs.desktop
        wget https://raw.githubusercontent.com/eccentric-j/doom-icon/master/cute-doom/doom.png -O "$ICON" &&
        sudo --preserve-env=ICON,DESKTOP_FILE sed -i "s|Icon=.*|Icon=$ICON|" $DESKTOP_FILE
      when: not has_doom_installed.stat.exists

- name: Install Dependencies For Doom
  dnf:
    name:
      - ripgrep
      - cmake
      - libtool
      - grip
      - shellcheck
      - tidy
      - shfmt
      - pandoc
      # - dockfmt
      # - stylelint
      # - js-beautify
    state: present
