---
- name: Install Stack
  dnf:
    name:
      - lua
      - fennel
      - clojure
      - npm
      - nodejs
      - containerd
      - podman
      - podman-compose
      - java-latest-openjdk
      - vagrant
    state: present
