---
- name: Set Private Symlink
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/.private_profile"
    "/{{ base_dir }}/{{ current_user }}/.private_profile"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.private_profile"
  notify: Reload Zsh Files

- name: Set Workstation Symlink (RC)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/.{{ workspace_id }}rc"
    "/{{ base_dir }}/{{ current_user }}/.{{ workspace_id }}rc"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.{{ workspace_id }}rc"
  notify: Reload Zsh Files

- name: Set Workstation Symlink (PROFILE)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/.{{ workspace_id }}_profile"
    "/{{ base_dir }}/{{ current_user }}/.{{ workspace_id }}_profile"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.{{ workspace_id }}_profile"
  notify: Reload Zsh Files

- name: Set Zsh Symlink (RC)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/.zshrc"
    "/{{ base_dir }}/{{ current_user }}/.zshrc"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.zshrc"
  notify: Reload Zsh Files

- name: Set Zsh Symlink (PROFILE)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/.zprofile"
    "/{{ base_dir }}/{{ current_user }}/.zprofile"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.zprofile"
  notify: Reload Zsh Files

- name: Set SBCL Symlink (RC)
  command: >
    ln -s -f
    "/{{ base_dir }}/{{ current_user }}/.dotfiles/.sbclrc"
    "/{{ base_dir }}/{{ current_user }}/.sbclrc"
  args:
    chdir: "/{{ base_dir }}/{{ current_user }}/.dotfiles"
    creates: "/{{ base_dir }}/{{ current_user }}/.sbclrc"
  notify: Reload Zsh Files
