---
- hosts: Workspace
  become: true

  vars_files:
    - vars/common.yml

  pre_tasks:
    - import_tasks: tasks/prelude.yml

  tasks:
    - import_tasks: tasks/common.yml
    - import_tasks: tasks/stack.yml
    - import_tasks: tasks/editor.yml
    - import_tasks: tasks/environment.yml
    - import_tasks: tasks/security.yml

  handlers:
    - import_tasks: handlers/common.yml
