---
- hosts: Workspace
  become: true

  vars_files:
    - vars/common.yml

  pre_tasks:
    - import_tasks: tasks/prelude.yml

  tasks:
    - import_tasks: tasks/common.yml
    - import_tasks: tasks/stack.yml
    - import_tasks: tasks/editor.yml
