#!/usr/bin/env bash

# Function to ping the workspace
ping() {
    cd "$1" || return
    ansible -i ../hosts.ini Workspace -c local -m ping
    return
}

# Function to ping the workspace
setup() {
    cd "$1" || return
    ansible-playbook -i ../hosts.ini -c local -K playbook.yml --ask-vault-pass
    return
}

install-darwin-dependencies() {
    [ ! -e /opt/homebrew/bin/ansible ] && brew install ansible
}

install-linux-dependencies() {
    [ ! -e /usr/bin/ansible ] && dnf install ansible
}

set-ssh-key-to-github() {
    gh auth login --with-token
    gh auth refresh -h github.com -s admin:ssh_signing_key
    gh ssh-key add "$HOME/.ssh/${CURRENT_USER}_rsa.pub" --type signing
}

# Main script logic
main() {
    local OS
    local FLAG
    OS="$(uname -a)"

    if [[ $OS =~ Darwin ]]; then
        OS="darwin"
    fi

    if [[ $OS =~ Linux ]]; then
        OS="linux"
    fi

    FLAG="$1+$OS"

    case "$FLAG" in
    "ping+darwin")
        install-darwin-dependencies
        ping ./darwin
        ;;
    "ping+linux")
        install-linux-dependencies
        ping ./linux
        ;;
    "setup+darwin")
        install-darwin-dependencies
        setup ./darwin
        ;;
    "setup+linux")
        install-linux-dependencies
        setup ./linux
        ;;
    github*)
        set-ssh-key-to-github
        ;;
    *)
        echo "Usage: $0 {ping|setup}"
        exit 1
        ;;
    esac
}

main "$1"
